version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: node_app_dev
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/userapp
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongodb_dev
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
